src/Entity/Location.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\LocationRepository")
 */
class Location
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="gps_x", type="decimal",precision=7, scale=5)
     * @Assert\NotBlank(message="Vous devez saisir une longitude")
     * @Assert\Type(
     *      type    = "float",
     *      message = "Vous devez saisir une longitude valide"
     * )
     */
    private $gpsX;

    /**
     * @ORM\Column(name="gps_y", type="decimal",precision=7, scale=5)
     * @Assert\NotBlank(message="Vous devez saisir une latitude")
     * @Assert\Type(
     *      type    = "float",
     *      message = "Vous devez saisir une latitude valide"
     * )
     */
    private $gpsY;

    /**
     * @ORM\Column(name="address", type="string", length=255)
     * @Assert\Type(
     *      type    = "string",
     *      message = "Vous devez saisir une chaine de caractère"
     * )
     */
    private $address;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getGpsX()
    {
        return $this->gpsX;
    }

    /**
     * @param mixed $gpsX
     *
     * @return self
     */
    public function setGpsX($gpsX)
    {
        $this->gpsX = $gpsX;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getGpsY()
    {
        return $this->gpsY;
    }

    /**
     * @param mixed $gpsY
     *
     * @return self
     */
    public function setGpsY($gpsY)
    {
        $this->gpsY = $gpsY;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * @param mixed $address
     *
     * @return self
     */
    public function setAddress($address)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getFormatedAddress()
    {
        $array = explode(',', $this->address);
        if (isset($array[1])) {
            return $array[1];
        } else {
            return $this->address;
        }
    }
}

src/Controller/Admin/ObservationController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Observation;
use App\Entity\Notification;
use App\Form\ObservationType;
use App\Form\ObserveBirdDetailType;
use App\Form\ObserveBirdMomentType;
use App\Repository\TaxrefRepository;
use App\Form\ObserveBirdLocationType;
use App\Repository\ObservationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;


/**
 * @Route("/admin/observation")
 * @Security("has_role('ROLE_USER')")
 */
class ObservationController extends Controller
{


    /**
     * Finds and displays all Observations entity of user.
     *
     * @Route("s/", name="admin_observation_index")
     * @Method("GET")
     * @Cache(smaxage="10")
     */
    public function index(ObservationRepository $observation)
    {
      $userObservations        = $observation->findByUser($this->getUser());
      $observationsToCheck     = $observation->findEqualToStatus(0);
      $uncommittedObservations = $observation->findLessThanOrEqualStatus(-200);

      return $this->render(
        'admin/observation/index.html.twig',
        compact('userObservations','observationsToCheck', 'uncommittedObservations')
      );
    }

    /**
     * Finds and displays a Observation entity.
     *
     * @Route("/{id}", requirements={"id": "\d+"}, name="admin_observation_show")
     * @Method("GET")
     * @Security("is_granted('show', observation)")
     */
    public function show(Observation $observation): Response
    {
        $taxref = $observation->getBird()->getTaxref();
        return $this->render('observation/show.html.twig',compact('taxref', 'observation'));
    }

    /**
     * @Route("/ajout", name="admin_observation_new")
     * @Method({"GET"})
     */
    public function new(SessionInterface $session)
    {
        return $this->redirectToRoute('admin_observation_new_step_1');
    }

    /**
     * @Route("/ajout/lieu", name="admin_observation_new_step_1")
     * @Method({"GET", "POST"})
     */
    public function stepOne(Request $request, SessionInterface $session, ObservationRepository $observation)
    {
        $session->set('step','1');
        if ($session->get('observation')) {
            $observation = $observation->find($session->get('observation'));
        } else {
            $observation = new Observation();
        }

        $form = $this->createForm(ObserveBirdLocationType::class, $observation);
        $options = [
            'page' => [
                "subtitle" => "étape 1 - lieu de l'observation"
            ],
            'form' => [
                "include_back_btn" => false,
                "back_btn_path"    => null
            ]
        ];

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $observation->setStatus(-101);
            $em = $this->getDoctrine()->getManager();
            $em->persist($observation);
            $em->flush();
            $session->set('observation', $observation->getId());

            return $this->redirectToRoute('admin_observation_new_step_2');
        }

        return $this->render('admin/observation/new.html.twig', [
            'options' => $options,
            'form' => $form->createView(),
            'observation' => $observation
        ]);
    }

    /**
     * @Route("/ajout/moment", name="admin_observation_new_step_2")
     * @Method({"GET", "POST"})
     */
    public function stepTwo(Request $request, SessionInterface $session, ObservationRepository $observation)
    {
        $session->set('step','2');
        $observation = $observation->find($session->get('observation'));
        $form = $this->createForm(ObserveBirdMomentType::class, $observation);
        $options = [
            'page' => [
                "subtitle" => "étape 2 - moment de l'observation",
            ],
            'form' => [
                "include_back_btn" => true,
                "back_btn_path"    => "admin_observation_new_step_1"
            ],
            'map' => [
                "address" => $observation->getLocation()->getAddress()
            ]
        ];

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $observation->setStatus(-102);
            $em = $this->getDoctrine()->getManager();
            $em->persist($observation);
            $em->flush();
            $session->set('observation', $observation->getId());

            return $this->redirectToRoute('admin_observation_new_step_3');
        }

        return $this->render('admin/observation/new.html.twig', [
            'options' => $options,
            'form' => $form->createView(),
            'observation' => $observation
        ]);
    }

    /**
     * @Route("/ajout/oiseau", name="admin_observation_new_step_3")
     * @Method({"GET", "POST"})
     */
    public function stepThree(Request $request, SessionInterface $session, ObservationRepository $observation)
    {

        $session->set('step','3');
        $observation = $observation->find($session->get('observation'));
        $form = $this->createForm(ObserveBirdDetailType::class, $observation);
        $options = [
            'page' => [
                "subtitle" => "étape 3 - détails de l'observation"
            ],
            'form' => [
                "include_back_btn" => true,
                "back_btn_path"    => "admin_observation_new_step_2"
            ],
            'map' => [
                "address" => $observation->getLocation()->getAddress()
            ]
        ];

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $observation->setStatus(-103);
            $em = $this->getDoctrine()->getManager();
            $em->persist($observation);
            $em->flush();
            $session->set('observation', $observation->getId());

            return $this->forward('App\Controller\Admin\ObservationController::stepFor');
        }

        return $this->render('admin/observation/new.html.twig', [
            'options' => $options,
            'form' => $form->createView(),
            'observation' => $observation
        ]);
    }

    /**
     * @Route("/ajout/reference/{id}", requirements={"id": "[1-9]\d*"}, name="admin_observation_new_step_4")
     * @Method({"GET", "POST"})
     */
    public function stepFor(
        Request $request,
        SessionInterface $session,
        TaxrefRepository $taxref,
        ObservationRepository $observation,
        int $id = null,
        AuthorizationCheckerInterface $authChecker
    ) {
        if (!$request->isXmlHttpRequest()) {
            $session->set('step', '4');
            $observation = $observation->find($session->get('observation'));

            if ($id) {

                $observation->getBird()->setTaxref($taxref->find($id));
                $observation->setUser($this->getUser());
                if (true === $authChecker->isGranted('ROLE_NATURALIST')) {
                    $observation->setStatus(1);
                } else {
                    $observation->setStatus(0);
                }

                $em = $this->getDoctrine()->getManager();
                $em->persist($observation);
                $em->flush();

                $session->remove('observation');
                $session->remove('step');

                $this->addFlash('success', 'Observation ajoutée avec succès !');

                return $this->redirectToRoute('admin_observation_show', ['id' => $observation->getId()]);
            }

            $posts = $taxref->findByFrType();
            $options = [
                'page' => [
                    "subtitle" => "étape 4 - choix de l'oiseau"
                ],
                'form' => [
                    "include_back_btn" => true,
                    "back_btn_path"    => "admin_observation_new_step_3"
                ],
                'map' => [
                    "address" => $observation->getLocation()->getAddress()
                ]
            ];
            return $this->render('admin/observation/new.html.twig',
                compact('posts', 'options','observation')
            );

        }

    }

    /**
     * @Route("/{id}/edit",requirements={"id": "\d+"}, name="admin_observation_edit")
     * @Method({"GET", "POST"})
     */
    public function edit(Request $request, Observation $observation)
    {
      $form = $this->createForm(ObservationType::class, $observation);
      $options = [
          'page' => [
              "title"    => "Edition de l'observation",
              "subtitle" => "Obs ID : " . $observation->getId(),
          ],
          'form' => [
              "action"           => "edit",
              "button_label"     => "Modifier",
              "include_back_btn" => true,
              "back_btn_path"    => "admin_observation_index",
              "back_btn_label"   => " ",
          ],
          'map' => [
              "address" => $observation->getLocation()->getAddress()
          ]
      ];

      $form->handleRequest($request);
      if ($form->isSubmitted() && $form->isValid()) {

        $em = $this->getDoctrine()->getManager();
        $em->persist($observation);
        $em->flush();

        $this->addFlash('success', 'Observation modifiée avec succès !');

        return $this->redirectToRoute('admin_observation_index');
      }

      return $this->render('admin/observation/edit.html.twig',[
        'form' => $form->createView(),

src/Controller/ObservationController.php
<?php

namespace App\Controller;

use App\Entity\Observation;
use App\Repository\TaxrefRepository;
use App\Repository\ObservationRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Cache;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

/**
 * @Route("/observation")
 */
class ObservationController extends Controller
{
    /**
     * @Route("s/", name="observation_index")
     * @Method("GET")
     * @Cache(smaxage="10")
     */
    public function index(Request $request, ObservationRepository $observation): Response
    {
        if (!$request->isXmlHttpRequest()) {
            $posts = $observation->findObservationsWithLimit();
            return $this->render('observation/index.html.twig', compact('posts'));
        }

        $offset      = $request->query->get('o', '');
        $foundTaxref = $observation->findObservationsWithLimit($offset);
        $results     = [];
        foreach ($foundTaxref as $k => $observation) {
            $results[$k] = [
                'page'         => 'observation',
                'id'           => htmlspecialchars($observation->getId()),
                'lbNomType'    => htmlspecialchars($observation->getBird()->getTaxref()->getLbNomType()),
                'lbAuteurType' => trim(htmlspecialchars($observation->getBird()->getTaxref()->getLbAuteurType()),'()'),
                'nomVernType'  => htmlspecialchars($observation->getBird()->getTaxref()->getNomVernType()),
                'user'         => htmlspecialchars($observation->getUser()->getName()) . " " . htmlspecialchars($observation->getUser()->getSurname()) ,
                'userUrl'      => htmlspecialchars($observation->getUser()->getPicture()->getUrl()),
                'userAlt'      => htmlspecialchars($observation->getUser()->getPicture()->getAlt()),
                'url'          => $observation->getBird()->getTaxref()->getPicture() ? htmlspecialchars($observation->getBird()->getTaxref()->getPicture()->getUrl()): null,
                'alt'          => $observation->getBird()->getTaxref()->getPicture() ? htmlspecialchars($observation->getBird()->getTaxref()->getPicture()->getAlt()): null,
                'ago'          => $observation->getAgo(date_format($observation->getdateObs(), 'Y-m-d H:i:s'))
            ];
            if ($results[$k]['url']) {
                $results[$k]['backgroundTable'] = '';
                $results[$k]['btnColor'] = 'btn-secondary';
            } else {
                $backgroundTable = ['table-info', 'table-danger','','','','',''];
                $results[$k]['backgroundTable'] = $backgroundTable[array_rand($backgroundTable,1)];
                if ($results[$k]['backgroundTable'] === '') {
                    $results[$k]['btnColor'] = 'btn-secondary';
                } else {
                    $results[$k]['btnColor'] = 'btn-white';
                }
            }
        }

        return $this->json($results);

    }

    /**
     * @Route("/{id}", requirements={"id": "\d+"}, name="observation_show")
     * @Method("GET")
     */
    public function show(Observation $observation): Response
    {
        $taxref = $observation->getBird()->getTaxref();
        return $this->render('observation/show.html.twig',compact('taxref', 'observation'));
    }

}

templates/components/tables/observation/_table_default.html.twig
<tr>
  <th scope="row">
    <i class="fa fa-circle fa-fw
      {% if obs.status == 1 %} text-primary
      {% elseif obs.status == 0 %} text-warning
      {% else %}text-danger
      {% endif %} ">
    </i>
    {{ obs.id }}
  </th>
  {% set col_address = obs.location.formatedAddress|trim|split(' ')%}
  {% if col_address %}
    <td>{% for row in col_address %}{{ row }}<br>{% endfor %}</td>
  {% else %}
  {% endif %}
  <td> {{ obs.getAgo(obs.dateObs|date()) }} </td>
  {% set col_taxref = obs.bird.taxref.lbNomType|trim|split(' ',2)%}
  <td>{% for row in col_taxref %}{{ row }}<br>{% endfor %}</td>
  <td>
    {% set col_status = obs.statusDefinition(obs.status)|split(',') %}
    {% if route == 'admin_home' %}
      {% for i_status,row in col_status if i_status == 0 %}{{ row }}{% endfor %}
    {% else %}
      {% for row in col_status %}{{ row }}<br>{% endfor %}
    {% endif %}
  </td>
  <td class="text-right">
    <a class="" href="{{ path('admin_observation_show',{ id: obs.id }) }}">
      <i class="fa fa-eye"></i>
    </a>
    {% if obs.status != 1 %}
      <a class="" href="{{ path('admin_observation_edit',{ id: obs.id }) }}">
        <i class="fa fa-pencil"></i>
      </a>
    {% endif %}
      {{ include('admin/observation/_delete_form.html.twig', {observation: obs}, with_context = false) }}
  </td>
</tr>

templates/components/tables/observation/_table_noValid.html.twig
<tr>
  <th scope="row">{{ obs.id }}</th>
  <td> {{obs.location.formatedAddress}} </td>
  <td> {{ obs.ago(obs.dateObs|date()) }} </td>
  <td> {{ obs.bird.taxref.lbNomType }} </td>
  <td>
      <i class="fa fa-circle fa-fw
        {% if obs.status == 1 %} text-primary
        {% elseif obs.status == 0 %} text-warning
        {% else %}text-danger
        {% endif %} ">
      </i>
      {{ obs.statusDefinition(obs.status) }}
    </td>
  <!-- actions -->
  <td class="text-right d-inline-flex justify-content-between">
    <a class="p-2" href="{{ path('home') }}"><i class="fa fa-eye"></i></a>
    {{ include('admin/observation/_check_form.html.twig', {observation: obs}, with_context = false) }}
  </td>
</tr>

templates/components/tables/observation/_table_toCheck.html.twig
<tr>
  <th scope="row">
    <i class="fa fa-circle fa-fw
      {% if obs.status == 1 %} text-primary
      {% elseif obs.status == 0 %} text-warning
      {% else %}text-danger
      {% endif %} ">
    </i>
    {{ obs.id }}
  </th>
  {% set col_2 = obs.location.formatedAddress|trim|split(' ')%}
  <td >{% for row in col_2 %}{{ row }}<br>{% endfor %}</td>
  <td> {{ obs.ago(obs.dateObs|date()) }} </td>
  {% set col_4 = obs.bird.taxref.lbNomType|trim|split(' ',2)%}
  <td>{% for row in col_4 %}{{ row }}<br>{% endfor %}</td>
  <td> {{ obs.user.name }} {{ obs.user.surname }} </td>
  <td>{{ obs.user.mail }} </td>
  <!-- actions -->
  <td class="text-right">
    <a class="p-2" href="{{ path('home') }}"><i class="fa fa-eye"></i></a>
    {{ include('admin/observation/_check_form.html.twig', {observation: obs}, with_context = false) }}
  </td>
</tr>

templates/components/tables/observation/default.html.twig
<div class="tab-pane fade {% if active|default(false) %}show active{% endif %}" id="{{ id }}Obs" role="tabpanel" aria-labelledby="{{ id }}-tab">
    <!-- <div class="row observation">
      <div class="col">
        <h6 class="text-light title">{{ title }} (affichage 1 à 6 de {{observations|length}} enregistrements)</h6>
      </div>
      <div class="col-auto">
        <a href="{{ path('admin_observation_new') }}" class="text-white btn btn-primary mt-0">
          <i class="fa fa-plus"></i>
          Ajouter
        </a>
      </div>
    </div> -->
    <div class="table-responsive">
      <table class="table table-striped table-light mt-3">
        <thead>
          <tr>
            <th scope="col">ID Observation</th>
            <th scope="col">Lieu</th>
            <th scope="col">Moment</th>
            <th scope="col">Oiseau</th>
            <th scope="col">Status</th>
            <th scope="col-action"></th>
          </tr>
        </thead>
        <tbody>
          {% if id == 'valid' %}
            {% for obs in observations if obs.status == 1  %}
              {{ include('components/tables/observation/_table_default.html.twig')}}
            {% endfor %}
          {% elseif id == 'wait' %}
            {% for obs in observations if obs.status == 0  %}
            {{ include('components/tables/observation/_table_default.html.twig')}}
            {% endfor %}
          {% else %}
            {% for obs in observations %}
              {{ include('components/tables/observation/_table_default.html.twig')}}
            {% endfor %}
          {% endif %}
        </tbody>
      </table>
    </div>
  </div>

templates/components/tables/observation/noValid.html.twig
<div class="tab-pane fade {% if active|default(false) %}show active{% endif %}" id="{{ id }}Obs" role="tabpanel" aria-labelledby="{{ id }}-tab">
    <table class="table table-striped table-light mt-3">
      <thead>
        <tr>
          <th scope="col">ID Observation</th>
          <th scope="col">Lieu</th>
          <th scope="col">Moment</th>
          <th scope="col">Oiseau</th>
          <th scope="col">Raison</th>
          <th scope="col-action"></th>
        </tr>
      </thead>
      <tbody>
        {% if id == 'uncommitted'%}
          {% for obs in observations %}
            {{ include('components/tables/observation/_table_noValid.html.twig')}}
          {% endfor %}
        {% else %}
          {% for obs in observations if obs.status <= -199  %}
            {{ include('components/tables/observation/_table_default.html.twig')}}
          {% endfor %}
        {% endif %}
      </tbody>
    </table>
  </div>

templates/components/tables/observation/old.html.twig
<div class="tab-pane fade {% if type == 'all' %}show active{% endif %}" id="{{ type }}Obs" role="tabpanel" aria-labelledby="{{ type }}-tab">
  <div class="row observation">
    <div class="col">
      <h6 class="title">{{ title }} (affichage 1 à 6 de 6 enregistrements)</h6>
    </div>
    <div class="col-auto">
      <a href="{{ path('admin_observation_new') }}" class="text-white btn btn-primary btn-round mt-0">
        <i class="fa fa-plus"></i>
        Ajouter
      </a>
    </div>
  </div>
  <table class="table table-striped table-light mt-3">
    <thead>
      <tr>
        <th scope="col">Obs ID</th>
        <th scope="col">Lieu</th>
        <th scope="col">Moment</th>
        <th scope="col">Oiseau</th>
        <th scope="col">Observateur</th>
        <th scope="col">Mail</th>
        <th scope="col-action"></th>
      </tr>
    </thead>
    <tbody>

        {% for obs in observations  %}
          <tr>
            <th scope="row">{{ obs.id }}</th>
            <td> {{obs.location.formatedAddress}} </td>
            <td> {{ obs.ago(obs.dateObs|date()) }} </td>
            <td> {{ obs.bird.taxref.lbNomType }} </td>
            <td> {{ obs.user.name }} {{ obs.user.surname }} </td>
            <td> <i class="fa fa-enveloppe-o fa-fw "></i>{{ obs.user.mail }} </td>
            <!-- actions -->
            <td class="text-right text-right d-inline-flex justify-content-between">
              <a class="p-2" href="{{ path('home') }}"><i class="fa fa-eye"></i></a>
              {{ include('admin/observation/_check_form.html.twig', {observation: obs}, with_context = false) }}
            </td>
          </tr>
        {% endfor %}
    </tbody>
  </table>
</div>

templates/components/tables/observation/toCheck.html.twig
<div class="tab-pane fade {% if active|default(false) %}show active{% endif %}" id="{{ id }}Obs" role="tabpanel" aria-labelledby="{{ id }}-tab">
  <table class="table table-striped table-light mt-3">
    <thead>
      <tr>
        <th scope="col">ID Observation</th>
        <th scope="col">Lieu</th>
        <th scope="col">Moment</th>
        <th scope="col">Oiseau</th>
        <th scope="col">Observateur</th>
        <th scope="col">Mail</th>
        <th scope="col-action"></th>
      </tr>
    </thead>
    <tbody>

        {% for obs in observations  %}
          {{ include('components/tables/observation/_table_toCheck.html.twig')}}
        {% endfor %}
    </tbody>
  </table>
</div>